## 넘파이 (numpy)

- 배열 계산 기능, 반올림, 버리기 기능 (floor, ceil, power 주요 함수 제공)

- 배열과 행렬을 쉽게 사용하게 해주는 패키지

- 속도가 매우 빠르고 응용 쉬움



In [1]:
import numpy as np

a = np.array([[2,3],[5,2]])
print(a)

[[2 3]
 [5 2]]


In [3]:
# 슬라이싱

d = np.array([[1,2,3,4,5],[2,4,6,8,10],[5,6,7,8,9]])

print(d)

print(d[1][2]) # [행] [열] 
print(d[1,2]) # 행, 열 
print(d[1:,3:]) # 1번 행부터 3번 열 끝까지 

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 5  6  7  8  9]]
6
6
[[ 8 10]
 [ 8  9]]


#### shape : 배열의 행과 열을 튜플로 반환

In [5]:
d = np.array([2,3,4,5,6])
print(d.shape)

d = np.array([[1,2,3,4,5,],[2,4,6,8,10]])
print(d.shape)


(5,)
(2, 5)


#### dtype & astype

- dtype 함수 사용하면 배열의 원소를 확인 할 수 있음.

- astype() 사용하면 배열의 원소 타입 변경 가능. 

In [10]:
data = np.arange(1,5) #배열의 범위 지정하는 함수
print(data)
data.astype('float64')
print(data)

[1 2 3 4]
[1 2 3 4]


#### np.zeros() , np.ones(), np.arange() 

- np.zeros() : 안의 내용을 다 0으로 만듦

- np.ones() : 안의 내용을 다 1로 만듦

- np.arange() : 범위 지정해서 증가시킴 ex. np.arange(2,10) -> 2부터 10앞까지 범위

In [11]:
print(np.zeros((1,5)))
print(np.ones((2,3)))

[[0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


#### np.transpose() : 행과 열을 바꾸는 배열 반환

In [12]:
a = np.ones((2,3))
print(a)

b = np.transpose(a) # 2행 3열 이었던 배열이 3행 2열로 바뀜.
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### 배열의 사칙연산
- 배열의 덧셈
: 배열의 같은 자리의 원소끼리 더해줌

- 배열의 곱셈
: 같은 자리의 원소끼리 곱함. 


In [13]:
arr1 = np.array([[2,3,4],[6,7,8]])
arr2 = np.array([[12,13,14],[36,47,58]])

In [15]:
#덧셈

print(arr1 + arr2)

#곱셈

print(arr1 * arr2)

#나눗셈

print(arr1 % arr2)

[[14 16 18]
 [42 54 66]]
[[ 24  39  56]
 [216 329 464]]
[[2 3 4]
 [6 7 8]]


In [19]:
# 크기가 서로 다른 배열끼리 더하기 
arr3 = ([100,200,300])

print(arr1 + arr3)


#행과 열의 크기가 다 다르면 오류 발생 
arr4 = np.array([1,2,3,4,5,6,7,8,9,10])
arr4.shape
arr1.shape

print(arr1 + arr4)

[[102 203 304]
 [106 207 308]]


ValueError: operands could not be broadcast together with shapes (2,3) (10,) 